algoritmo "Lista 6 - exerc 1"
//Faça o exercício 01 novamente, dessa vez, utilizando a estrutura de repetição para-faça.
var
num: vetor [1..5] de inteiro
contadora: inteiro
inicio
// Seção de Comandos
para contadora de 1 ate 5 passo 1 faca
   escreva("Por favor, digite um número inteiro: ")
   leia(num[contadora])
fimpara
para contadora de 1 ate 5 passo 1 faca
   escreval("",contadora,"º número:",num[contadora],"")
fimpara
fimalgoritmo
